# Form implementation generated from reading ui file '.\first_stage.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1422, 794)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.current_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.current_image.setGeometry(QtCore.QRect(10, 10, 1050, 331))
        self.current_image.setMouseTracking(False)
        self.current_image.setObjectName("current_image")
        self.next_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(980, 360, 51, 51))
        self.next_button.setObjectName("next_button")
        self.previous_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(10, 360, 51, 51))
        self.previous_button.setObjectName("previous_button")
        self.previous_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.previous_image.setGeometry(QtCore.QRect(10, 430, 1050, 331))
        self.previous_image.setObjectName("previous_image")
        self.open_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(80, 360, 151, 51))
        self.open_button.setObjectName("open_button")
        self.save_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(800, 360, 151, 51))
        self.save_button.setObjectName("save_button")
        self.add_parametrs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_parametrs.setGeometry(QtCore.QRect(1050, 710, 151, 51))
        self.add_parametrs.setObjectName("add_parametrs")
        self.unstage_parametrs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.unstage_parametrs.setGeometry(QtCore.QRect(1260, 710, 151, 51))
        self.unstage_parametrs.setObjectName("unstage_parametrs")
        self.image_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.image_name.setGeometry(QtCore.QRect(240, 380, 341, 16))
        self.image_name.setObjectName("image_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1422, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_button.setText(_translate("MainWindow", ">"))
        self.previous_button.setText(_translate("MainWindow", "<"))
        self.open_button.setText(_translate("MainWindow", "Открыть"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
        self.add_parametrs.setText(_translate("MainWindow", "Применить"))
        self.unstage_parametrs.setText(_translate("MainWindow", "Назад"))
        self.image_name.setText(_translate("MainWindow", "Название изображения"))
