"""update_migration

Revision ID: 764234815853
Revises: 5272f25192d6
Create Date: 2024-08-30 22:08:50.192150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764234815853'
down_revision = '5272f25192d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True, comment='файл'),
    sa.Column('jpg_name', sa.String(), nullable=True, comment='название jpg фала'),
    sa.Column('marking_name', sa.String(), nullable=True, comment='название jpg фала'),
    sa.ForeignKeyConstraint(['file_id'], ['sirius.file.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sirius'
    )
    op.drop_constraint('file_metadata_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'file_metadata', ['metadata_id'], ['id'], source_schema='sirius', referent_schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', schema='sirius', type_='foreignkey')
    op.create_foreign_key('file_metadata_id_fkey', 'file', 'file_metadata', ['metadata_id'], ['id'])
    op.drop_table('train_data', schema='sirius')
    # ### end Alembic commands ###
