"""update_migration

Revision ID: c6fcadcc9127
Revises: 8aeebccc7729
Create Date: 2024-08-22 18:29:58.718300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fcadcc9127'
down_revision = '8aeebccc7729'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('dilatation_x', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('dilatation_y', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('dilatation_iteration', sa.Integer(), nullable=True), schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'dilatation_iteration', schema='sirius')
    op.drop_column('file_metadata', 'dilatation_y', schema='sirius')
    op.drop_column('file_metadata', 'dilatation_x', schema='sirius')
    # ### end Alembic commands ###
