"""update_migration

Revision ID: 8aeebccc7729
Revises: f332963dd5b8
Create Date: 2024-08-22 18:08:29.256668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aeebccc7729'
down_revision = 'f332963dd5b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('eroz_x', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('eroz_y', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('eroz_iteration', sa.Integer(), nullable=True), schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'eroz_iteration', schema='sirius')
    op.drop_column('file_metadata', 'eroz_y', schema='sirius')
    op.drop_column('file_metadata', 'eroz_x', schema='sirius')
    # ### end Alembic commands ###
