"""update_migration

Revision ID: f332963dd5b8
Revises: 117c15e8e50d
Create Date: 2024-08-22 01:07:10.410430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f332963dd5b8'
down_revision = '117c15e8e50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('gaus_core_x', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('gaus_core_y', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('gaus_sigma_x', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('gaus_sigma_y', sa.Integer(), nullable=True), schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'gaus_sigma_y', schema='sirius')
    op.drop_column('file_metadata', 'gaus_sigma_x', schema='sirius')
    op.drop_column('file_metadata', 'gaus_core_y', schema='sirius')
    op.drop_column('file_metadata', 'gaus_core_x', schema='sirius')
    # ### end Alembic commands ###
