"""initial_migration

Revision ID: 117c15e8e50d
Revises: 
Create Date: 2024-08-16 01:42:41.665335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117c15e8e50d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sirius'
    )
    op.create_table('file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='id родительского файла'),
    sa.Column('metadata_id', sa.Uuid(), nullable=True, comment='метадата'),
    sa.Column('is_final_image', sa.Boolean(), nullable=True, comment='финальное изображение'),
    sa.Column('previous_file', sa.Uuid(), nullable=True, comment='предыдущее изображение'),
    sa.ForeignKeyConstraint(['metadata_id'], ['sirius.file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sirius'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file', schema='sirius')
    op.drop_table('file_metadata', schema='sirius')
    # ### end Alembic commands ###
