"""update_migration

Revision ID: 4a2da12b421f
Revises: c6fcadcc9127
Create Date: 2024-08-22 19:30:24.164136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2da12b421f'
down_revision = 'c6fcadcc9127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('bilat_d', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('bilat_color', sa.Integer(), nullable=True), schema='sirius')
    op.add_column('file_metadata', sa.Column('bilat_coord', sa.Integer(), nullable=True), schema='sirius')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'bilat_coord', schema='sirius')
    op.drop_column('file_metadata', 'bilat_color', schema='sirius')
    op.drop_column('file_metadata', 'bilat_d', schema='sirius')
    # ### end Alembic commands ###
